num(number) 以及 基础运算

In [6]:
x=3
y=6
x **=2
x *= 3
y += 1
print(x+1, x+3, y+5, y-7)

28 30 12 0


bool(boolean) 以及逻辑判断

In [9]:
t = True
f = False
print(type(t))
print(t and f)
print(t or f)
print(not f)
print(t != f) # XOR

<class 'bool'>
False
True
True
True


string 及其操作

In [ ]:
hello = 'hello' 
world = "world"
print(len(hello))
print(hello + ' '+ world)
hw26 ='%s %s %d' % (hello, world, 26) # 字符串格式化 (String Formatting)
print(hw26)

5
hello world
hello world 26


In [31]:
hello = 'hello' 
print(hello.capitalize())
print(hello.upper())
print(hello.rjust(7)) #当变量原字符串数量少于7的时候，向右平移直到该变量有7位字符串为止，用空格在字符串前面补齐，超过7位字符串的时候保持原位不动
print(hello.center(7)) #扩展为7位字符串，并且原字符串居中
print(hello.replace('e', 'aaa'))
print(hello.replace('l','(aoa)'))
print('hello world'.strip()) #去除字符串前后（leading and trailing）空格，但是中间的空格不动.

Hello
HELLO
  hello
 hello 
haaallo
he(aoa)(aoa)o
hello world


### Containers(list, dictionary, sets, tuples)

Lists

In [ ]:
ls = [3, '1', 2, 2] # 不会自动合并相同的元素。 list永远是', '（逗号加空格）
print(ls, ls[1], ls[-1]) #ls[NUM]里面的NUM是从0开始计数的，选取数组的第NUM+1位
print(type(ls[1]))
ls[2] = 5
print(ls)
ls.append('beer')
print(ls)
last_one = ls.pop() #删掉最后一位, 并且返回删掉的哪一位数
print(ls,last_one)

[3, '1', 2, 2] 1 2
<class 'str'>
[3, '1', 5, 2]
[3, '1', 5, 2, 'beer']
[3, '1', 5, 2] beer


In [89]:
#Slicing of Lists
nums = list(range(5)) #range是一个内置的创建一个list的函数，从0开始数。此时num为[0, 1, 2, 3, 4]
print(nums)
print(nums[2:4]) #nums[NUM1:NUM2],取左闭右开。
print(nums[2:])
print(nums[:])
print(nums[:-1]) #还是左闭右开
nums[2:4] = [8,9,10] # 不一定要位数完全一致，不一致也可以替换
print(nums)
squares = []
for num in range(5):
    squares.append(num **2)
print(squares)
cond_squres =[i ** 2 for i in range(5) if i % 2 == 0] #conditional operation
print(cond_squres)
cond_squres_dict ={i : i ** 2 for i in range(5) if i % 2 == 0} #conditional operation
print(cond_squres_dict)
    

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 10, 4]
[0, 1, 4, 9, 16]
[0, 4, 16]
{0: 0, 2: 4, 4: 16}


In [ ]:
fruits = ['apple', 'banana', 'cherry', 26]
for fruit in fruits: # fruit是临时变量，for循环每次吧fruits这个list里面的一个元素按顺序提取出来赋值给fruit
    print(fruit)
for idx, fruit in enumerate(fruits): #enumerate 返回一个迭代器，每次循环都会吐出一个包含两个元素的元组 (Tuple)：(索引, 元素)其中索引从1开始
    print('@%d: %s'% (idx+1, fruit))

apple
banana
cherry
26
@1: apple
@2: banana
@3: cherry
@4: 26


Dictionaries

In [ ]:
dict = {'cat':'cute', 'dog':'furry', 'dog':'furry'}
print(dict) # 相同的自动合并
print(dict['dog'])
n = 'cat' in dict
print(n, type(n))
dict['fish'] = 'smelly'
print(dict)
print(dict.get('monkey','N/A'))
print(dict.get('fish','N/A')) #DICT.get 如果前者能找到，那么就print该value，否则就是后面那个默认的key
del dict['fish']
print(dict.get('fish','N/A'))

{'cat': 'cute', 'dog': 'furry'}
furry
True <class 'bool'>
{'cat': 'cute', 'dog': 'furry', 'fish': 'smelly'}
N/A
smelly
N/A


In [ ]:
#Loops
dict = {'person': 2, 'cat': 4, 'spider': 8}
for animal in dict:
    leg = dict[animal]
    print('a %s has %d legs.' % (animal, leg))
for animal, legs in dict.items(): #两个临时变量，前者是key, 后者是value.
    print('a %s has %d legs.' % (animal, legs))

a person has 2 legs.
a cat has 4 legs.
a spider has 8 legs.
a person has 2 legs.
a cat has 4 legs.
a spider has 8 legs.


Sets

In [102]:
fruits = {'apple', 'banana', 'cherry', 'cherry'}# 会合并相同的元素
print(fruits)
print('apple' in fruits)
print('durain' in fruits)
fruits.add('durain') #Set.add('Element')，在整个Set的前面加上这个元素。
print('durain' in fruits)
print(len(fruits))
for idx, fruit in enumerate(fruits):
    print('#%d: %s' % (idx + 1, fruit))


{'banana', 'apple', 'cherry'}
True
False
True
4
#1: durain
#2: banana
#3: apple
#4: cherry


In [ ]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)} # int(NUM)代表着强制转换，在放入set之后被去重了
print(nums)  # Prints "{0, 1, 2, 3, 4, 5}"

{0, 1, 2, 3, 4, 5}


Tuples

In [106]:
dict= {(x, x+1):x for x in range(10)}
t = (5, 6)
print(dict[t])
print(type(t))
print(dict[(2,3)])

5
<class 'tuple'>
2


## Functions

函数使用def定义

In [109]:
def sign(x):
    if x > 0:
        print('positive')
    elif x < 0:
        print('negative')
    else:
        print('zero')
for num in [-1,0,114514]:
    sign(num)

negative
zero
positive


In [110]:
def sign(x):
    if x > 0:
        return('positive')
    elif x < 0:
        return('negative')
    else:
        return('zero')
for num in [-1,0,114514]:
    print(sign(num))

negative
zero
positive


In [ ]:
def sign(x):
    if x > 0:
        print('positive')

    elif x < 0:
        print('negative')

    else:
        print('zero')

for num in [-1,0,114514]:

    print(sign(num))# 每循环一次会有2个输出，第一个是sign函数内部的输出，然后因为sign函数没有返回值，所以默认返回None被主函数print出来

negative
None
zero
None
positive
None


Optional Keyword Arguments（可选关键字参数）

In [6]:
def hello(name, loud = False):
    if loud:
        print('Hello, %s'% name.upper())
    else:
        print('Hello, %s'% name)
hello('Bob')
hello('Davis',loud= True)    

Hello, Bob
Hello, DAVIS


## Classes(面向对象编程)

In [15]:
class Greeter(object):
    
    def __init__(self, name): #__init__两个下划线，self是一个内置参数？，代表实例对象本身
        self.name = name #通过这个操作把传入的名字存进这个对象里面
    def greet(self, loud = False):#类内部定义的函数称为方法，同样的第一个参数一定要是self才能访问该对象内部的数据
        if loud:
            print('Hello, %s'% self.name.upper())
        else:
            print('Hello, %s'% self.name)
g = Greeter('Fred') #把Fred存进这一类
print(g.name)
g.greet()
g.greet(loud=True)

Fred
Hello, Fred
Hello, FRED


# Numpy

## Arrays(数组)
1. 是一个“同质且多维”的数据矩阵。它将相同类型的数据紧密排列在内存中，通过“形状（Shape）”来组织维度，从而实现极速的批量计算和坐标引用。

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
print(a[1])
a[1]=3
print(a)

b = np.array([[1,2,3],(4,5,6)]) #内部方括号和小括号都可以，array会自动转成方括号
print(b.shape)
print(b[1])

<class 'numpy.ndarray'>
(3,)
2
[1 3 3]
(2, 3)
[4 5 6]


2. 更多的array操作：

In [ ]:
import numpy as np

a = np.zeros((2,2))# 全0矩阵，其中0的type是numpy.float64
print(a)

b = np.ones((2,2)) # 全1矩阵，其中1的type是numpy.float64
print(b)
print(type(b[1][1])) #使用多个中括号索引可以索引到具体的数
print(b[1,1]) #作用同上

c = np.full((2, 2), 7)
print(c)

d = np.eye(2) #单位矩阵，括号里面是这个单位矩阵的rank，同样里面所有的数类型都是numpy.float64
print(d)

e = np.random.random((2,2)) #随机生成一个（x，y）维矩阵。第一个random是numpy里面的一个模块，第二个random是random模块里面的函数名。
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
1.0
1.0
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.98542398 0.38565961]
 [0.69435091 0.60710677]]


3. slicing of array（矩阵切片）

In [ ]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

b = a[:2, 1:3] #对a进行切片（先看第几行，再看第几列，行or列左闭右开）
print(b)

b[0,0] = 99
print(a[0,1]) #会发现改变b的话a也会相应变化，可以认为b是在a上面开了一个窗口，去窥探a这块的取值

a[1, 1] = 66
print(b[1,0])

c = a[:2, 1:5] #索引超出实际的范围不会报错，而是自动把超过的范围忽略，认定窗口打开到边界。
print(c)

a_col2 = a[:, 1] #如果对于行或者列的索引没有‘：’则会默认只需要一行（列），矩阵会降维成一维矩阵
e = a[1:2,:]
print(d, d.shape)# shape展示列（行数），
print(e, e.shape)

[[2 3]
 [6 7]]
99
66
[[99  3  4]
 [66  7  8]]
[99 66 10] (3,)
[[ 5 66  7  8]] (1, 4)


4. array indexing：从数组中提取几个数组成新的数组

In [35]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[[0, 1, 2],[0, 1, 2]]
#等价于
c = np.array([a[0, 0], a[1, 1], a[2, 2]])# 注意加上方括号
d = a[[0, 0],[1, 1]] #相同的索引会重复导出数字
print(b)
print(c)
print(d)


[ 1  6 11]
[ 1  6 11]
[2 2]


5. 快速修改特定位置的值

In [ ]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

b = [0, 1, 0]
print(a[np.arange(3),b])# np.range()的参数是扫过被探视函数的总行数,逗号后面的矩阵是各个行需要提取的数的列数。

a[np.arange(3),b] += 10 #对索引地址的数整体操作。
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 6 9]
[[11  2  3  4]
 [ 5 16  7  8]
 [19 10 11 12]]


6. Boolean array indexing：布尔类型矩阵

In [1]:
import numpy as np
a = np.array([[1,4],[2,5],[-114514,1919810]])
bool_idx = (a > 2)
print(bool_idx)

print(a[bool_idx]) #只有对应位置是True 的留下，结果会降维成一维矩阵

print(a[a > 2]) #囊括了上述的内容，是上述内容的简单写法

[[False  True]
 [False  True]
 [False  True]]
[      4       5 1919810]
[      4       5 1919810]


Datatypes in numpy(for numbers):为了兼容C，适配了不同精度以及signed，unsigned的int，不同精度的float，不同精度的complex，bool_,string， unicode，void。

In [ ]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.float64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int64
float64
float16


Array Maths

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64) #全部都是对位的算法

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array， usually 8位小数
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


矩阵的点乘（Inner Product）

In [10]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce REAL NUMBER 219
print(v.dot(w))
print(np.dot(v, w))
print(type(v.dot(w)))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(type(v.dot(x)))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(type(y.dot(x)))

219
219
<class 'numpy.int64'>
[29 67]
[29 67]
<class 'numpy.ndarray'>
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
<class 'numpy.ndarray'>


在对行与列进行加法的时候axis=0代表对列求和，axis=1代表对行求和。

In [9]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


转置（rank 1 array transposes to itself）

In [11]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


### Broadcasting
span a low-dimension array to higher-dimension without really creating a new matrix.

麻烦方法：

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise


'''
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v
'''


print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


简单表示方法：

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [17]:
import numpy as np

v_col = np.array([[10], [20], [30]]) # (3, 1)
v_row = np.array([[1, 2, 3]])       # (1, 3)
result = v_col + v_row
print(result)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


从两个数组的右侧（后方）维度开始对比，两个数字要么相等，要么其中一个是 1。如果不满足，就不能加。

reshape

In [18]:
import numpy as np

a = np.arange(6) # 生成 [0, 1, 2, 3, 4, 5]
# 把 6 个元素变成 2 行 3 列
b = a.reshape((2, 3))
print(b)
# 输出:
# [[0 1 2]
#  [3 4 5]]

[[0 1 2]
 [3 4 5]]


In [ ]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2) #"*"是对位相乘

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


# SciPy

进行高深的数学，信号等等运算的

In [ ]:
from scipy.misc import imread, imsave, imresize

# Read an JPEG image into a numpy array
img = imread('assets/bluecat.jpg')
print(img.dtype, img.shape)  # Prints "uint8 (400, 248, 3)"

# We can tint the image by scaling each of the color channels
# by a different scalar constant. The image has shape (400, 248, 3);
# we multiply it by the array [1, 0.95, 0.9] of shape (3,);
# numpy broadcasting means that this leaves the red channel unchanged,
# and multiplies the green and blue channels by 0.95 and 0.9
# respectively.
img_tinted = img * [1, 0.95, 0.9]

# Resize the tinted image to be 300 by 300 pixels.
img_tinted = imresize(img_tinted, (300, 300))

# Write the tinted image back to disk
imsave('assets/bluecat_tinted.jpg', img_tinted)

# Matplotlib